default[:vagrant_developer][:gitconfig_source]="gitconfig"
default[:vagrant_developer][:gitconfig_destination]="/home/vagrant/.gitconfig"
default[:vagrant_developer][:gitignore_source]="gitignore"
default[:vagrant_developer][:gitignore_destination]="/home/vagrant/.gitignore"
default[:vagrant_developer][:screenfile_source]="screenrc"
default[:vagrant_developer][:screenfile_destination]="/home/vagrant/.screenrc"
